name: Build & Deploy DEB to GitHub Pages

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_deb:
    name: Build DEB Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GPG
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg.conf
          gpg --list-keys

      - name: Install dpkg-dev
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev debhelper

      - name: Build .deb package
        run: |
          mkdir -p build
          dpkg-deb --build . build/lums.deb
          echo "Built package at build/lums.deb"

      - name: Sign .deb package
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          debsign -k $(gpg --list-keys --with-colons | awk -F: '/^pub/ {print $5}') build/lums.deb

  deploy_pages:
    name: Deploy to GitHub Pages
    needs: build_deb
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Copy built package
        run: |
          mkdir -p deb
          cp build/lums.deb deb/

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add deb/lums.deb
          git commit -m "Deploy lums.deb for $GITHUB_REF"
          git push origin gh-pages
